//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementSqlite
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public long StudentId { get; set; }
        public string StudentName { get; set; }
        public string Department { get; set; }
        public string Year { get; set; }
        public string Semester { get; set; }
        public string ContactNo { get; set; }
    }
}
